### ISSUE TITLE
[Question]: Joint project

### ISSUE THREAD

**Issue by IvanIsak2000** [mb6ockatf/mb6ockatf#6]
I know that you are busy now, I suggest starting some interesting joint project in your free time, if you don't mind, you can suggest topics  😊

**Comment by mb6ockatf** [comment]
> I offer a GUI application 👀

sounds interesting) you mean a webapplication or just a gui program? webapplications are much easier to develop rather than something like PyQT4 or that library you used in blockchain

**Comment by IvanIsak2000** [comment]
By the way, I wanted to ask how busy are you at the moment?
